#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("DangerouslyDelicious.Resource", IsApplication=true)]

namespace DangerouslyDelicious
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int theme_custom_background = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int theme_devicedefault_background = 2131034113;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int AppleWormIcon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int badapple = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int goodapple = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_arrow_back_white_24dp = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int mdpi_yelp_powered_btn_light = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int yelp_review_btn_light = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070040
			public const int backHomeButton = 2131165248;
			
			// aapt resource value: 0x7f070018
			public const int comparisonDangerText = 2131165208;
			
			// aapt resource value: 0x7f070024
			public const int comparisonDeliciousText = 2131165220;
			
			// aapt resource value: 0x7f07001a
			public const int comparisonGrade = 2131165210;
			
			// aapt resource value: 0x7f07001e
			public const int comparisonInspectedOn = 2131165214;
			
			// aapt resource value: 0x7f07001f
			public const int comparisonInspectionDate = 2131165215;
			
			// aapt resource value: 0x7f07002a
			public const int comparisonNumberReviews = 2131165226;
			
			// aapt resource value: 0x7f070028
			public const int comparisonNumberStars = 2131165224;
			
			// aapt resource value: 0x7f070012
			public const int comparisonRestaurantAddress = 2131165202;
			
			// aapt resource value: 0x7f070011
			public const int comparisonRestaurantName = 2131165201;
			
			// aapt resource value: 0x7f07001c
			public const int comparisonScore = 2131165212;
			
			// aapt resource value: 0x7f070014
			public const int comparisonSection = 2131165204;
			
			// aapt resource value: 0x7f070010
			public const int comparisonSpace2 = 2131165200;
			
			// aapt resource value: 0x7f070013
			public const int comparisonSpace3 = 2131165203;
			
			// aapt resource value: 0x7f07000f
			public const int comparisonSubheader = 2131165199;
			
			// aapt resource value: 0x7f07000b
			public const int comparisonTopSpace = 2131165195;
			
			// aapt resource value: 0x7f070020
			public const int comparisonVerticalSpace = 2131165216;
			
			// aapt resource value: 0x7f070026
			public const int comparisonYelpStars = 2131165222;
			
			// aapt resource value: 0x7f070017
			public const int dangerSpace1 = 2131165207;
			
			// aapt resource value: 0x7f070019
			public const int dangerSpace2 = 2131165209;
			
			// aapt resource value: 0x7f07001b
			public const int dangerSpace3 = 2131165211;
			
			// aapt resource value: 0x7f07001d
			public const int dangerSpace4 = 2131165213;
			
			// aapt resource value: 0x7f070015
			public const int dangerousColumn = 2131165205;
			
			// aapt resource value: 0x7f070016
			public const int dangerousIcon = 2131165206;
			
			// aapt resource value: 0x7f070021
			public const int deliciousColumn = 2131165217;
			
			// aapt resource value: 0x7f070022
			public const int deliciousIcon = 2131165218;
			
			// aapt resource value: 0x7f070025
			public const int deliciousSpace1 = 2131165221;
			
			// aapt resource value: 0x7f070023
			public const int deliciousSpace1a = 2131165219;
			
			// aapt resource value: 0x7f070029
			public const int deliciousSpace2 = 2131165225;
			
			// aapt resource value: 0x7f070027
			public const int deliciousSpace2b = 2131165223;
			
			// aapt resource value: 0x7f07002b
			public const int deliciousSpace3 = 2131165227;
			
			// aapt resource value: 0x7f07002d
			public const int deliciousSpace4 = 2131165229;
			
			// aapt resource value: 0x7f070001
			public const int gifImageView = 2131165185;
			
			// aapt resource value: 0x7f070045
			public const int headerRow = 2131165253;
			
			// aapt resource value: 0x7f070006
			public const int homeHeader = 2131165190;
			
			// aapt resource value: 0x7f070002
			public const int loadingSearchText = 2131165186;
			
			// aapt resource value: 0x7f070000
			public const int locationSpace1 = 2131165184;
			
			// aapt resource value: 0x7f070004
			public const int mainScreenIcon = 2131165188;
			
			// aapt resource value: 0x7f070007
			public const int mainSpace2 = 2131165191;
			
			// aapt resource value: 0x7f070009
			public const int mainSpace3 = 2131165193;
			
			// aapt resource value: 0x7f07000c
			public const int navRow = 2131165196;
			
			// aapt resource value: 0x7f07002c
			public const int readReviewsButton = 2131165228;
			
			// aapt resource value: 0x7f07003c
			public const int restaurantSearchBox = 2131165244;
			
			// aapt resource value: 0x7f07002e
			public const int resultFooterRow = 2131165230;
			
			// aapt resource value: 0x7f07000d
			public const int returnToListButton = 2131165197;
			
			// aapt resource value: 0x7f07000e
			public const int returnToListText = 2131165198;
			
			// aapt resource value: 0x7f070042
			public const int returnToSearchButton = 2131165250;
			
			// aapt resource value: 0x7f070043
			public const int returnToSearchText = 2131165251;
			
			// aapt resource value: 0x7f07003f
			public const int searchFooterRow = 2131165247;
			
			// aapt resource value: 0x7f07003a
			public const int searchHeader = 2131165242;
			
			// aapt resource value: 0x7f07000a
			public const int searchLocationButton = 2131165194;
			
			// aapt resource value: 0x7f070036
			public const int searchNumberReviews = 2131165238;
			
			// aapt resource value: 0x7f070035
			public const int searchRestaurantAddress = 2131165237;
			
			// aapt resource value: 0x7f070032
			public const int searchRestaurantName = 2131165234;
			
			// aapt resource value: 0x7f070046
			public const int searchResultHeader = 2131165254;
			
			// aapt resource value: 0x7f070044
			public const int searchResultSpace = 2131165252;
			
			// aapt resource value: 0x7f070003
			public const int searchResultSpace1 = 2131165187;
			
			// aapt resource value: 0x7f070005
			public const int searchResultSpace1b = 2131165189;
			
			// aapt resource value: 0x7f070048
			public const int searchResultSpace2 = 2131165256;
			
			// aapt resource value: 0x7f070041
			public const int searchResultTopSpace = 2131165249;
			
			// aapt resource value: 0x7f070030
			public const int searchRows = 2131165232;
			
			// aapt resource value: 0x7f070038
			public const int searchScreenIcon = 2131165240;
			
			// aapt resource value: 0x7f070037
			public const int searchSpace1 = 2131165239;
			
			// aapt resource value: 0x7f07003b
			public const int searchSpace1a = 2131165243;
			
			// aapt resource value: 0x7f070039
			public const int searchSpace1b = 2131165241;
			
			// aapt resource value: 0x7f07003d
			public const int searchSpace2 = 2131165245;
			
			// aapt resource value: 0x7f070031
			public const int searchSubrow1 = 2131165233;
			
			// aapt resource value: 0x7f070034
			public const int searchSubrow2 = 2131165236;
			
			// aapt resource value: 0x7f07003e
			public const int searchYelpButton = 2131165246;
			
			// aapt resource value: 0x7f070033
			public const int searchYelpStars = 2131165235;
			
			// aapt resource value: 0x7f07002f
			public const int startOverButton = 2131165231;
			
			// aapt resource value: 0x7f070008
			public const int useCurrentButton = 2131165192;
			
			// aapt resource value: 0x7f070047
			public const int yelpIcon = 2131165255;
			
			// aapt resource value: 0x7f070049
			public const int yelpSearchResultList = 2131165257;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int FindByLocation = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int RatingsViolationsComparison = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int SearchList = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int SearchYelp = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int YelpSearchResult = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040004
			public const int ApplicationName = 2130968580;
			
			// aapt resource value: 0x7f040002
			public const int readReviews = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int searchLocation = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int searchYelp = 2130968579;
			
			// aapt resource value: 0x7f040000
			public const int useCurrent = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int DDCustomTheme = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
