#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("DangerouslyDelicious.Resource", IsApplication=true)]

namespace DangerouslyDelicious
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int AppleWormIcon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_arrow_back_white_24dp = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int mdpi_yelp_powered_btn_light = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int SkullIcon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int yelp_review_btn_light = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050011
			public const int comparisonDangerText = 2131034129;
			
			// aapt resource value: 0x7f050015
			public const int comparisonDeliciousText = 2131034133;
			
			// aapt resource value: 0x7f05001b
			public const int comparisonNumberReviews = 2131034139;
			
			// aapt resource value: 0x7f050019
			public const int comparisonNumberStars = 2131034137;
			
			// aapt resource value: 0x7f05000c
			public const int comparisonRestaurantAddress = 2131034124;
			
			// aapt resource value: 0x7f05000b
			public const int comparisonRestaurantName = 2131034123;
			
			// aapt resource value: 0x7f05000e
			public const int comparisonSection = 2131034126;
			
			// aapt resource value: 0x7f050008
			public const int comparisonSpace1 = 2131034120;
			
			// aapt resource value: 0x7f05000a
			public const int comparisonSpace2 = 2131034122;
			
			// aapt resource value: 0x7f05000d
			public const int comparisonSpace3 = 2131034125;
			
			// aapt resource value: 0x7f050009
			public const int comparisonSubheader = 2131034121;
			
			// aapt resource value: 0x7f050012
			public const int comparisonVerticalSpace = 2131034130;
			
			// aapt resource value: 0x7f050017
			public const int comparisonYelpStars = 2131034135;
			
			// aapt resource value: 0x7f05000f
			public const int dangerousColumn = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int dangerousIcon = 2131034128;
			
			// aapt resource value: 0x7f050013
			public const int deliciousColumn = 2131034131;
			
			// aapt resource value: 0x7f050014
			public const int deliciousIcon = 2131034132;
			
			// aapt resource value: 0x7f050016
			public const int deliciousSpace1 = 2131034134;
			
			// aapt resource value: 0x7f05001a
			public const int deliciousSpace2 = 2131034138;
			
			// aapt resource value: 0x7f050018
			public const int deliciousSpace2b = 2131034136;
			
			// aapt resource value: 0x7f05001c
			public const int deliciousSpace3 = 2131034140;
			
			// aapt resource value: 0x7f05001e
			public const int deliciousSpace4 = 2131034142;
			
			// aapt resource value: 0x7f05002f
			public const int headerRow = 2131034159;
			
			// aapt resource value: 0x7f050003
			public const int homeHeader = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int loadingSearchResults = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int loadingSearchText = 2131034113;
			
			// aapt resource value: 0x7f050004
			public const int mainSpace2 = 2131034116;
			
			// aapt resource value: 0x7f050006
			public const int mainSpace3 = 2131034118;
			
			// aapt resource value: 0x7f05002b
			public const int navRow = 2131034155;
			
			// aapt resource value: 0x7f05001d
			public const int readReviewsButton = 2131034141;
			
			// aapt resource value: 0x7f050028
			public const int restaurantSearchBox = 2131034152;
			
			// aapt resource value: 0x7f05002c
			public const int returnToSearchButton = 2131034156;
			
			// aapt resource value: 0x7f05002d
			public const int returnToSearchText = 2131034157;
			
			// aapt resource value: 0x7f050027
			public const int searchHeader = 2131034151;
			
			// aapt resource value: 0x7f050007
			public const int searchLocationButton = 2131034119;
			
			// aapt resource value: 0x7f050025
			public const int searchNumberReviews = 2131034149;
			
			// aapt resource value: 0x7f050024
			public const int searchRestaurantAddress = 2131034148;
			
			// aapt resource value: 0x7f050021
			public const int searchRestaurantName = 2131034145;
			
			// aapt resource value: 0x7f050030
			public const int searchResultHeader = 2131034160;
			
			// aapt resource value: 0x7f05002e
			public const int searchResultSpace = 2131034158;
			
			// aapt resource value: 0x7f050002
			public const int searchResultSpace1 = 2131034114;
			
			// aapt resource value: 0x7f050032
			public const int searchResultSpace2 = 2131034162;
			
			// aapt resource value: 0x7f05001f
			public const int searchRows = 2131034143;
			
			// aapt resource value: 0x7f050026
			public const int searchSpace1 = 2131034150;
			
			// aapt resource value: 0x7f050029
			public const int searchSpace2 = 2131034153;
			
			// aapt resource value: 0x7f050020
			public const int searchSubrow1 = 2131034144;
			
			// aapt resource value: 0x7f050023
			public const int searchSubrow2 = 2131034147;
			
			// aapt resource value: 0x7f05002a
			public const int searchYelpButton = 2131034154;
			
			// aapt resource value: 0x7f050022
			public const int searchYelpStars = 2131034146;
			
			// aapt resource value: 0x7f050005
			public const int useCurrentButton = 2131034117;
			
			// aapt resource value: 0x7f050031
			public const int yelpIcon = 2131034161;
			
			// aapt resource value: 0x7f050033
			public const int yelpSearchResultList = 2131034163;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int FindByLocation = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int RatingsViolationsComparison = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int SearchList = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int SearchYelp = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int YelpSearchResult = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040004
			public const int ApplicationName = 2130968580;
			
			// aapt resource value: 0x7f040002
			public const int readReviews = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int searchLocation = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int searchYelp = 2130968579;
			
			// aapt resource value: 0x7f040000
			public const int useCurrent = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
